################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
    - title: Introduction
      link:
      open: true
      sections:
        - title: Exchange 
          link: docs/introduction/exchange-intro.md
        - title: Exchange APIs
          link: docs/introduction/exchange-apis.md
- sections:
  - title: Additional API Info
    link: docs/getting-started/api-info.md
    open: true
    sections:
    - title: Virtual account operations
      link: docs/getting-started/account-operations.md
    - title: Submerchant onboarding
      link: docs/getting-started/boarding.md
    - title: Funding
      link: docs/getting-started/funding.md
    - title: Information retrieval
      link: docs/getting-started/information-retrieval.md
    - title: Authentication
      link: docs/getting-started/oauth.md
    - title: Pricing + Equipment offerings
      link: docs/getting-started/offerings.md
    - title: OFAC and Credit risk checks
      link: docs/getting-started/risk.md
    - title: Split funding by transaction 
      link: docs/getting-started/split-details.md
    - title: Transaction operations 
      link: docs/getting-started/transactions.md
    - title: Reporting & Settlement 
      link: docs/getting-started/reporting.md
- sections:
    - title: Guide documentation
      link: docs/introduction/exchange-boarding-guide.md
      open: true
      sections:
        - title: Add application sample
          link: docs/introduction/samples/add_application.md
        - title: Add outlet sample
          link: docs/introduction/samples/add_outlet.md
        - title: Application status check sample
          link: docs/introduction/samples/application_status_check.md
        - title: Application submit sample
          link: docs/introduction/samples/application_submit.md
        - title: Merchant boarding sample
          link: docs/introduction/samples/boarding_merchant.md
        - title: Retrieve application sample
          link: docs/introduction/samples/retrieve_application.md
- sections:
  - title: Release notes
    sections:
    - title: June 2022
      link: docs/release-notes/2022/june.md
