################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Exchange is a platform that brings together  functionality required by a payment facilitator or marketplace to manage their sub-merchants. This includes offer management and onboarding configuration, merchant onboarding, underwriting, flexible funding options, and reporting.
getStarted: /docs/introduction/exchange-intro.md
benefits:
  - title: Boarding
    description: Fast end-to-end sub-merchant onboarding avaliable through suite of APIs and UI.
    icon: assets/images/business_icon_square.png
  - title: Funding
    description:  Direct splits for payouts to sub-merchants and beneficiaries through funding instructions.
    icon: assets/images/money_icon_square.png
  - title: Settlement 
    description: Settlement details and reporting avaliable through Exchange.
    icon: assets/images/statement_icon_square.png
guides:
  - title: Boarding API guide
    description: Boarding a standard location through our API
    link: docs/getting-started/boarding.md
featuredFeatures:
  - title: Payment Facilitators
    featured: true
    description:  Supporting payment faciliators services and requirments
    relatedDocs:
      - link: /docs/getting-started/boarding.md
        title: Sub-merchant boarding
      - link: docs/getting-started/funding.md
        title: Funding
      - link: docs/getting-started/reporting.md 
        title: Reporting & Settlement
  - title: Marketplaces
    featured: true
    description:  Supporting Marketplace offerings with split payments
    relatedDocs:
      - link: /docs/getting-started/boarding.md
        title: Sub-merchant boarding
      - link: docs/getting-started/funding.md
        title: Funding
      - link: docs/getting-started/reporting.md 
        title: Reporting & Settlement
  - title: PayFac Lite
    featured: true
    description:  Supporting PayFac Lite 
    relatedDocs:
      - link: /docs/getting-started/boarding.md
        title: Sub-merchant boarding
      - link: docs/getting-started/funding.md
        title: Funding
      - link: docs/getting-started/reporting.md 
        title: Reporting & Settlement
  - title: Boarding
    groupName: API Suite
    description:  End-to-end boarding API 
    relatedDocs:
      - link: /docs/getting-started/boarding.md
        title: Sub-merchant boarding
      - link: docs/getting-started/funding.md
        title: Funding
      - link: docs/getting-started/reporting.md 
        title: Reporting & Settlement
    relatedAPIs: 
      - type: post       
        path: /boarding/add_application
        title: Add Application
  - title: Funding
    groupName: API Suite
    description:  Funding instructions and split details that can be sent through API.
    relatedDocs:
      - link: docs/getting-started/funding.md
        title: Instruct funding
    relatedAPIs: 
      - type: post
        title: Funding Instruction       
        path: /funding/instruction        
  - title: Reporting & Settlement
    groupName: API Suite
    description:   Settlement details and reporting avaliable through Exchange.
    relatedDocs: 
        - link: /docs/getting-started/reporting.md  
          title: Reporting
    relatedAPIs: 
      - type: post
        title: Get Settlement Info    
        path: /account/settlement-info   
