################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Exchange is a platform that brings together  functionality required by a payment facilitator or marketplace to manage their sub-merchants. This includes offer management and onboarding configuration, merchant onboarding, underwriting, flexible funding options, and reporting.
getStarted: /docs/getting-started/getting-started-overview.md
benefits:
  - title: PayFacs
    description: Supporting Enterprise PayFac Business 
    icon: assets/images/business_icon_square.png
  - title: Marketplaces
    description:  Supporting Marketplace solutions
    icon: assets/images/money_icon_square.png
  - title: PayFac Lite 
    description: Supporting PayFac Lite 
    icon: assets/images/statement_icon_square.png
featuredFeatures:
  - title: Boarding
    groupName: API Suite
    description:  End-to-end boarding API 
    relatedDocs:
      - link: /docs/getting-started/getting-started-boarding.md
        title: Sub-merchant boarding
    relatedAPIs: 
      - type: post       
        path: /boarding/add_application
  - title: Underwriting
    groupName: API Suite
    description:  Supporting Underwriting + Monitoring through our API
    relatedDocs:
      - link: docs/getting-started/getting-started-underwriting.md
        title: Sub-merchant boarding
    relatedAPIs: 
      - type: post       
        path: /intelligence/decision
  - title: Funding
    groupName: API Suite
    description:   Fund submerchants through exchange
    relatedDocs: 
        - link: /docs/getting-started/funding.md
          title: Funding
    relatedAPIs: 
      - type: post
        title: Funding Instruction
        path: /funding/instruction
  - title: Reporting
    groupName: API Suite
    description:   View Reporting for submerchants funding + fees through Exchange
    relatedDocs: 
        - link: /docs/getting-started/getting-started-reporting.md  
          title: Reporting
    relatedAPIs: 
      - type: post
        title: Get Account Summary    
        path: /account/account-summary   
  - title: Transactions
    groupName: API Suite
    description:  View transactions and splits applied via the systems automated funding 
    relatedDocs:
      - link: docs/getting-started/getting-started-transactions.md
        title: Instruct funding
    relatedAPIs: 
      - type: post
        title: Search Transactions       
        path: /transaction
  - title: Maintenance
    groupName: API Suite
    description:  Perform submerchant maintenance for pricing through API
    relatedDocs:
      - link: docs/getting-started/getting-started-maintenance.md
        title: Instruct funding
    relatedAPIs: 
      - type: post
        title: Update Maintenance Case       
        path: //maintenance  
