################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Exchange
  productionDescription: Exchange is a platform that brings together  functionality required by a payment facilitator or marketplace to manage their sub-merchants. This includes offer management and onboarding configuration, merchant onboarding, underwriting, flexible funding options, and reporting.
  whoIsItFor: Payment Facilitators, Marketplaces
  getStarted: /docs/exchange-intro.md
benefits:
  - title: Boarding
    description: Fast end-to-end sub-merchant onboarding avaliable through suite of APIs and UI.
  - title: Funding
    description:  Direct splits for payouts to sub-merchants and beneficiaries through funding instructions.
  - title: Reconciliation 
    description: Settlement details and reporting avaliable through Exchange.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv logo
featuredFeatures:
  - title: Payment Facilitators
    groupName: Product offerings
    featured: true
    description:  End-to-end digital solution for Payment Facilitators and Marketplaces. 
    tags: ["boarding", "funding", "settlement", "reporting"]
    bullets: ["boarding", "funding", "settlement", "reporting"]  
    relatedDocs:
      - relatedDoc: 
        title: Sub-merchant boarding
        description: End-to-end sub-merchant onboarding is avaliable through API and UI.
        link: /docs/getting-started/boarding.md
      - relatedDoc: 
        title: Funding
        description: Funding instructions and split details that can be sent through API.
        link: /docs/getting-started/funding.md
      - relatedDoc: 
        title: Reporting & Settlement
        description: Settlement details and reporting avaliable through Exchange.
        link: /docs/getting-started/reporting.md
    relatedAPIs:
      - relatedAPI: 
        title: Add Application
        description: Add a new Merchant application
        type: "post"        
        path: "/merchant/application"
      - relatedAPI: 
        title: Funding Instruction
        description: Send Funding Instruction
        type: "post"        
        path: "/v1/funding/instruction"
      - relatedAPI: 
        title: Get Settlement Info
        description: Retrieve settlement information
        type: "post"        
        path: "/account/settlement-info"
  - title: Marketplaces
    groupName: Product offerings
    featured: true
    description:  End-to-end digital solution for Payment Facilitators and Marketplaces. 
    tags: ["boarding", "funding", "settlement", "reporting"]
    bullets: ["boarding", "funding", "settlement", "reporting"]  
    relatedDocs:
      - relatedDoc: 
        title: Sub-merchant boarding
        description: End-to-end sub-merchant onboarding is avaliable through API and UI.
        link: /docs/getting-started/boarding.md
      - relatedDoc: 
        title: Funding
        description: Funding instructions and split details that can be sent through API.
        link: /docs/getting-started/funding.md
      - relatedDoc: 
        title: Reporting & Settlement
        description: Settlement details and reporting avaliable through Exchange.
        link: /docs/getting-started/reporting.md
    relatedAPIs:
      - relatedAPI: 
        title: Add Application
        description: Add a new Merchant application
        type: "post"        
        path: "/merchant/application"
      - relatedAPI: 
        title: Funding Instruction
        description: Send Funding Instruction
        type: "post"        
        path: "/v1/funding/instruction"
      - relatedAPI: 
        title: Get Settlement Info
        description: Retrieve settlement information
        type: "post"        
        path: "/account/settlement-info"
